env:
  LIB_DIR: lib
  LIB_NAME: types

name: Publish @guildxyz/$LIB_NAME

on:
  push:
    branches:
      - $default-branch
    paths:
      - "$LIB_DIR/$LIB_NAME/**/*.ts"

defaults:
  run:
    working-directory: ./$LIB_DIR/$LIB_NAME

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: |
          git config --global user.email "cs-balazs@users.noreply.github.com"
          git config --global user.name "cs-balazs"
      - run: npm version patch
      - run: git add .
      - run: git commit -m "@guildxyz/$LIB_NAME version"
      - run: git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
